### ISSUE TITLE
Missing features on url-wasm

### ISSUE THREAD

**Issue by anonrig** [anonrig/url#1]
I've added this issue as a reference for future commiters/contributers. Here's the missing features from the URL-WASM library to be spec compliance.

## Documentation

- [x] Update README and mention url-wasm@alpha for beta testing the application
- [x] Release an initial benchmark

## URLSearchParams

- [x] new URLSearchParams('hello=world') - @anonrig
- [ ] URLSearchParams encoding checks for compliance - @nebarf
- [ ] URLSearchParams iterator support for entries, keys etc. - @nebarf
- [ ] URLSearchParams.forEach - 3rd parameter is missing. It should return `this` - @nebarf

## URL

- [ ] URL.searchParams should return URLSearchParams instance.
- [ ] URL.hash parsing - @anonrig
- [ ] URL.host parsing
- [ ] URL.hostname parsing
- [ ] URL.href parsing
- [ ] URL.origin parsing
- [ ] URL.password parsing
- [ ] URL.pathname parsing
- [ ] URL.port parsing
- [x] URL.protocol parsing - @anonrig
- [ ] URL.search parsing (and integrating with URLSearchParams) - @anonrig

**Comment by nebarf** [comment]
I'd like to contribute. Do you have any preference/priority? Are you already working on any of the missing features above?

Feel free to reach me in the Node.js Slack channel under my name and surname.

**Comment by anonrig** [comment]
Hi @nebarf,

You can start any of the items from the list. I'll have some time to work on it this weekend and will update the issue before I start any of the tasks. If you tell which issue you're working on, I'll also update the board according to it. Thanks!
