### ISSUE TITLE
Last tests failing

### ISSUE THREAD

**Issue by yannh** [anonrig/url#6]
Unfortunately the result of the Github Actions is only kept for a few months... Should I be worried about the tests not passing? Is this _somewhat_ working and okay to use in hobby projects, or is breakage to be expected? Thanks!!

**Comment by anonrig** [comment]
There's only 1 test failing for this package and it is documented on the readme. You can safely use it on your hobby projects. Thanks for asking!

**Comment by anonrig** [comment]
Actually, I don’t recommend using this in any production applications. It’s far from perfect.

**Comment by yannh** [comment]
Thanks for the heads up :heart:
